### ISSUE TITLE
Documentation url

### ISSUE THREAD

**Issue by laurentlb** [wix/exodus#15]
The readme says:

> See the documentation [here](https://wix-incubator.github.io/exodus/). 

But this link doesn't work anymore, I get a 404 error (but it worked a few days ago). Was it moved?

**Comment by natansil** [comment]
Sorry about that. The repo was moved from `wix-incubator` to `wix` org and only after that all the links were fixed.
Should be fine now.

**Comment by Adityashah2003** [comment]
can you please link the latest documentation.
