### ISSUE TITLE
Project is not building with Bazel 1.0.1

### ISSUE THREAD

**Issue by stahloss** [wix/exodus#23]
Any plans to make exodus Bazel 1.0+ compatible?

Trying to build the source with Bazel 1.0.1 using `bazel build //migrator/wix-bazel-migrator:migrator_cli_deploy.jar`

`ERROR: Analysis of target '//migrator/wix-bazel-migrator:migrator_cli_deploy.jar' failed; build aborted: Analysis of target '@scalac_rules_commons_io//:scalac_rules_commons_io' failed; build aborted`

**Comment by natansil** [comment]
Thanks @D0rmouse!
rules_scala version needs to be updated.
https://github.com/wix/exodus/blob/master/WORKSPACE#L25

any chance you can try to update it and report back?
seems like you can just take the head commit:
https://github.com/bazelbuild/rules_scala#bazel-compatible-versions

**Comment by stahloss** [comment]
Thanks for the advice :)

HEAD didn't work, but I updated to this and now it builds.
```
rules_scala_version="0f89c210ade8f4320017daf718a61de3c1ac4773" # update this as needed
rules_scala_version_sha256="37eb013ea3e6a940da70df43fe2dd6f423d1ac0849042aa586f9ac157321018d"
```

**Comment by natansil** [comment]
Great!
If you could be so kind to open a PR with your change, that would be amazing :)

**Comment by stahloss** [comment]
I would like to and I tried, but I am unable to push my branch to remote:

```
$ git push -u origin feature/update_rules_scala_version
remote: Permission to wix/exodus.git denied to D0rmouse.
fatal: unable to access 'https://github.com/wix/exodus.git/': The requested URL returned error: 403
```

**Comment by natansil** [comment]
Have you tried to push for your fork.
1. create a fork with the github button
2. add a remote to it in your local clone: `git remote add fork git@github.com:natansil/exodus.git`
3. run `git push -u fork feature/update_rules_scala_version`

**Comment by stahloss** [comment]
Cheers, PR raised.

**Comment by natansil** [comment]
Thank you! merged.
Can I close this issue?

**Comment by stahloss** [comment]
Done!
