### ISSUE TITLE
Exodus failing because one of the jar doesn't have pom in it

### ISSUE THREAD

**Issue by aman1k4** [wix/exodus#54]
The error message is:
===== Please double check that you have no typos.
if you REALLY meant to reference this jar and you know it exists even though there IS NO pom,
please rerun the tool with --ignoreMissingDependencies flag at the end =====

I have verified the jar exists but the pom is not in the jar. 

Can anyone please help me.

**Comment by natansil** [comment]
@or-shachar is this an error from AetherResolver?
Following our conversation - another example why Exodus should move away from Aether to something else...
In the meantime why do we have ignoreMissingDependencies = false [here](https://github.com/wix/exodus/blob/master/dependency-resolver/maven-dependency-resolver/src/main/scala/com/wixpress/build/maven/AetherMavenDependencyResolver.scala#L62)

**Comment by aman1k4** [comment]
@natansil Is there any workaround for this? I tried adding a dummy pom but it get's stuck on it. 
Is there any specific field it expects?
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.google.apis</groupId>
  <artifactId>google-api-services-cloudcommerceprocurement</artifactId>
  <version>v1-rev20190531-1.25.0-SNAPSHOT</version>
</project>
```

**Comment by natansil** [comment]
I'm not sure it would help, but can you try and change this line:
https://github.com/wix/exodus/blob/master/dependency-resolver/maven-dependency-resolver/src/main/scala/com/wixpress/build/maven/AetherMavenDependencyResolver.scala#L62
`withSession(ignoreMissingDependencies = false` => `withSession(ignoreMissingDependencies = true`
re-build and run?

**Comment by aman1k4** [comment]
Thanks. Will try this.

**Comment by aman1k4** [comment]
One of the dependencies we use didn't have pom.xml and it was failing because of that. The change suggested by @natansil works.
