### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by pcj** [wix/exodus#62]
Seems like it has been awhile since last release.  Any plans for a new one?

**Comment by natansil** [comment]
@or-shachar do you know the status of the refactoring/moving to Java?

**Comment by or-shachar** [comment]
Still waiting for a contribution around this.
But is it really a release holder?

**Comment by natansil** [comment]
Do we have something we want to release?

**Comment by pcj** [comment]
It's not blocking me as I ~~can~~ did clone and build from source, but I noticed that it's been some time since you did a release (it's what the documentation recommends to download)

**Comment by natansil** [comment]
@or-shachar can you please review https://github.com/wix/exodus/pull/55 so I can merge it.
After that we can do a new release I guess

**Comment by natansil** [comment]
done https://github.com/wix/exodus/releases/tag/v0.2
